package config

// DefaultConcurrency ...
var DefaultConcurrency int

// TargetEnvironment ...
var TargetEnvironment string

// TargetApplication ...
var TargetApplication string

// WarnUnencrypted ...
var WarnUnencrypted bool
